[greeter]
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
cursor-theme-name=Adwaita
background=/usr/share/openfang/wallpaper.png
default-user-image=/usr/share/openfang/avatar.png
hide-user-image=false
show-clock=true
clock-format=%A %B %-d  ·  %H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~power
position=50%,center 50%,center
panel-position=top
