[Seat:*]
# Default session
user-session=xfce
greeter-session=lightdm-gtk-greeter

# Autologin on live environment
# Comment these out after installing to disk
autologin-user=ai
autologin-user-timeout=0
autologin-session=xfce

# Greeter settings
greeter-hide-users=false
allow-guest=false
